linters:
  enable-all: true
  disable:
    - depguard
    - errname
    - exhaustivestruct
    - exhaustruct
    - nosnakecase
    - testpackage

linters-settings:
  exhaustive:
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
  varnamelen:
    ignore-decls:
      - ok bool
      - w http.ResponseWriter
