language: go

go:
  - '1.11'
  - '1.12'

env:
  global:
    - GO111MODULE=on

go_import_path: arnested.dk/go/dsupdate

before_install:
  - GO111MODULE=off go get -u github.com/robertkrimen/godocdown/godocdown
  - GO111MODULE=off go get -u github.com/frapposelli/wwhrd
  - curl -sSL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make doc ; git diff --exit-code # Check the docs are up to date
  - go generate ; git diff --exit-code # Check generated code is up to date
  - go test -v -race -coverprofile=c.out -covermode=atomic ./...
  - ln c.out coverage.txt # Cover profile should be detected by both CodeClimate and CodeCov
  - go mod vendor && wwhrd check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Refresh godoc.org documentation
  - provider: script
    script: 'curl -sS -X POST -H "Content-Type: application/x-www-form-urlencoded" https://godoc.org/-/refresh --data "path=arnested.dk%2Fgo%2Fdsupdate"'
    on:
      repo: arnested/go-dsupdate
      branch: master
  # Refresh goreportcard.com report and cached report card badge.
  - provider: script
    script: 'curl -sSL -X POST -H "Content-Type: application/x-www-form-urlencoded" https://goreportcard.com/checks --data "repo=arnested.dk%2Fgo%2Fdsupdate"; curl -sSL -X PURGE https://camo.githubusercontent.com/72d31d7b07d65a450126fc734ada298b2fb45343/68747470733a2f2f676f7265706f7274636172642e636f6d2f62616467652f61726e65737465642e646b2f676f2f64737570646174652f'
    on:
      repo: arnested/go-dsupdate
      branch: master
