language: go

go:
  - '1.12'

env:
  global:
    - GO111MODULE=on

go_import_path: arnested.dk/go/dsupdate

before_install:
  - GO111MODULE=off go get github.com/robertkrimen/godocdown/godocdown
  - GO111MODULE=off go get github.com/frapposelli/wwhrd
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make doc ; git diff --quiet # Check the docs are up to date
  - go test -v -race -coverprofile c.out ./...
  - go mod vendor && wwhrd check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  # Refresh godoc.org documentation
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://godoc.org/-/refresh --data "path=arnested.dk%2Fgo%2Fdsupdate"'
    on:
      repo: arnested/go-dsupdate
      branch: master
  # Refresh goreportcard.com report
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://goreportcard.com/checks --data "repo=arnested.dk%2Fgo%2Fdsupdate"'
    on:
      repo: arnested/go-dsupdate
      branch: master
