on:
  push:
    branches:
      - main
    tags:
      - v*
name: Refresh badges etc.
jobs:
  refresh_badges:
    runs-on: ubuntu-latest
    steps:
    - name: Purge badges from GitHub cache
      run: |
        for u in $(curl --silent https://github.com/arnested/go-dsupdate | grep https://camo.githubusercontent.com/ | sed -E 's|.*"(https://camo\.githubusercontent\.com/[^"]+)".*|\1|'); do
          echo curl --silent -X PURGE "$u"
        done
