name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arnested/go-version-action@v1
        id: go-version
      - name: Install Go ${{ steps.go-version.outputs.minimal }}
        uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version: ${{ steps.go-version.outputs.minimal }}
      - name: Go version
        run: go version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          skip-go-installation: true
