on: push
name: Build and test
jobs:
  build_and_test:
    name: Build and test
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.11', '1.12', '1.13']
    steps:
    - uses: actions/checkout@master
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: go test
      env:
        GO111MODULE: 'on'
      run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt ./...
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1.0.3
      env:
        CODECOV_ENV: ${{ matrix.go-version }}
      with:
        token: ${{secrets.CODECOV_TOKEN}}
  license_check:
    name: License check
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Install wwhrd
      env:
        GO111MODULE: 'off'
      run: go get -u github.com/frapposelli/wwhrd
    - name: go mod vendor
      env:
        GO111MODULE: 'on'
      run: go mod vendor
    - name: wwhrd check
      run: $(go env GOPATH)/bin/wwhrd check
